#!/bin/bash
set -ueo pipefail

# Updates the secret file in Kubernetes
# Takes the secret file as the first argument

readonly SECRET_NAME='goon-auth-secret'
readonly SECRET=$(cat ${1} | base64 -w0)

echo 'Updating goon_auth secrets ...'

kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
data:
  secrets.json: ${SECRET}
EOF

