---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: murmur
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: murmur
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/murmur
          imagePullPolicy: Always
          name: murmur
          volumeMounts:
            - name: murmur-certs
              mountPath: /etc/murmur/tls
            - name: murmur-storage
              mountPath: /var/lib/mumble-server
            - name: murmur-config
              mountPath: /etc/murmur
          ports:
            - containerPort: 64738
        - image: gcr.io/goonswarm-1303/murmur-ldap:e077831
          name: murmur-ldap
          args:
            - /etc/murmur/murmur-ldap.conf
          volumeMounts:
            - name: murmur-config
              mountPath: /etc/murmur
          resources:
            requests:
              cpu: 50m
      volumes:
        - name: murmur-certs
          secret:
            secretName: tendollarbond-com-tls
        - name: murmur-config
          configMap:
            name: murmur-config
        - name: murmur-storage
          gcePersistentDisk:
            pdName: murmur-storage
